"""add_google_facebook_id_to_users

Revision ID: e866b3c4038f
Revises: d9392caddf96
Create Date: 2026-01-08 15:23:25.684811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e866b3c4038f'
down_revision: Union[str, Sequence[str], None] = 'd9392caddf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_detail', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order_detail', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'receiver_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('facebook_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'google_id')
    op.alter_column('orders', 'receiver_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('order_detail', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_detail', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
